### ISSUE TITLE
General discussion thread

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#109]
This is a thread for the discussion of anything CWE development related.

**Comment by ARR8** [comment]
This is more of a Vic2 question: Does anyone know how localization encoding is supposed to work? It seems that localization files are ANSI encoded, but the game seems to choke on any non-ASCII ANSI characters, like those with accents. However, that doesn't seem right, since Vic2 natively supports languages with plenty of accents. The vanilla files seem to be partly ANSI and partly some unknown encoding. Are special characters simply locked out of the English localization?

**Comment by EmperorRAG** [comment]
I was taking a look at how Victoria 2 does calculations involving pops and I saw that the mods performance could be improved. If you were to make craftsmen and capitalists stay only in the state capital, you would reduce pop fracturing. The reduction of pop fractures would decrease the amount of calculations required for pops in the game session which would increase the game's performance. The proposed change would also tie into the urbanization patterns that follow industrialization therefore making the mod more realistic. Additionally you can go further and make it so that all pop types besides farmers, teachers, laborers, entrepreneurs and aristocrats only present in the state capital. The results of the additional change should greatly increase performance as well as aid the game in performing pop promotion and demotion. The most noticeable impact from the changes will most likely be reduced RAM usage, although it would be dependent on the user's pc.

**Comment by settintotrieste** [comment]
@EmperorRAG This is an interesting method to approach the performance issues however there are some concerns that I have with it. The first is that by limiting the promotion of craftsmen to only state capitals, a craftsmen promotion bottleneck is formed which can severely reduce the rate of overall craftsmen promotion which might in turn slow down economic growth uneccessarily and penalises nations with more provinces but fewer states which would mean more re-balancing of the economy. The second concern that I have is that NWO tried this approach previously but apparently abandoned it to the best of my knowledge which implies that they may have encountered a major problem with such a setup which I don't know of. The potential problems for the other pop types would also be the same as for the craftsmen.

**Comment by EmperorRAG** [comment]
Sorry I wasn't able to explain it better, I was hopping onto a flight. I had implemented this before on your mod awhile ago to see if it was viable but I haven't tried it on NWO. To address the first concern; the pop promotion to craftsmen isn't limited to state capitals, pops in all provinces will continue to promote to craftsmen but on promotion will teleport to the capital. This is what happened when I tested it before, the system has already been in place for soldier pops on your mod as well. Second concern; for NWO it is on hold as the code hasn't been removed but commented. The process to get this change done would require the replacement of the affected pops to the state capital in each start date , otherwise the game will crash. This is probably the reasoning for why it is on hold for NWO as it would take some time to do. I hope this addresses your concerns, there is also another benefit to the proposed changes. Pops' needs are better represented as there is less clashing between the pops that should be in the same grouping but are not. By less clashing I mean that the allocation of the income is distributed more accurately and the benefit of this is that it requires less calculations for the game. The result again is better performance for the user and an improvement to the game economy.

**Comment by EmperorRAG** [comment]
If by demographics you mean the populations sizes, culture and religion, then there wouldn't need to be any demographic changes. All that needs to be done is the changing of pop types; so an example could be 5000 craftsmen in a non-state capital province being changed to farmers/laborers and then in the state capital province changing 5000 farmers/laborers to craftsmen. The crash comes from the pop type needing to be in a state capital province but due to it not being in the state capital province the game crashes, this issue is caused from the pop types not being teleported to the state capital province as they weren't promoted or demoted. From my current knowledge, craftsmen don't have to be in the province where the factory is as they appear to be added to a state craftsmen pool that factories can use for employees; I don't think it will create problems.

**Comment by ARR8** [comment]
By demographics I had more in mind employment and the actual pop type, but I guess I have no problem with it if the totals are the same like you suggested.

I see that state_capital_only is a built-in property of pops, which in vanilla is applied to aristocrats, capitalists, and bureaucrats, so there's no chance of editing the migration logic.
  So, if it's true that he game crashes if state_capital_only pops aren't only in the state capital, that will have to be manually fixed for the start dates.

However, there is an alternative. The migration factors already includes some urbanization logic:
>`	modifier = { factor = -1 location = { is_state_capital = yes } }`
>`	modifier = { factor = -1.0 OR = { type = farmers type = labourers } }`

What we can do is strengthen this heavily for the desired pop types, so that they will probably migrate to some state capital on their own. If needed, we can also add a push for farmers and labourers in state capitals or those with urban terrain for a "ruralization" though I imagine this isn't as necessary.

In either case, what I would recommend is creating a separate issue and quoting some of the highlights of the discussion so we don't clutter this thread. I do think it's a good idea, especially since it looks like the mod has disabled state_capital only for the vanilla poptypes who have it.

**Comment by EmperorRAG** [comment]
I think it would be counter intuitive to add in migration modifiers as it would defeat the purpose of trying to optimize the game; the whole point is to reduce the number of calculations that the game needs to make.

**Comment by ARR8** [comment]
That's a good point. The migration approach would still lower calculations by merging pops, but it is unnecessary and not preferable if the former is possible. I would still move this to a new issue for more discussion, though I think we can say the built-in approach is the better of the two.

**Comment by makotech222** [comment]
As USA, i get like 100 of those 'Bankrupt country, please send money' events. Is there anyway to either

a. Automatically give the money (usually i have too much) or auto decline without popping up event
b. Stop countries from asking you so much

**Comment by ARR8** [comment]
Hi @makotech222, are you using the latest GitHub snapshot or the release?
  We've recently made some changes that should prevent some bankruptcies and lower their frequency overall.

**Comment by makotech222** [comment]
Maybe about a weeks ago I downloaded from github. 

Another weird thing is, as USA, sometimes i get alliance requests from Russia

**Comment by ARR8** [comment]
@makotech222 - Try the latest version, since we've taken some measured to prevent bankruptcies further. We probably won't automate the requests since countries should only go bankrupt very rarely. Russia is more likely to offer an alliance if another power is rank 2. If Russia is rank 2, that's a problem and something we should look into.

@settintotrieste - Do you have any preference whether party names should be in their native language/transliterated into Latin or translated to English? We should probably be consistent. I'm leaning toward translation for consistency unless we can figure out how to write accent marks

**Comment by settintotrieste** [comment]
@ARR8 - I prefer to use the English translation for the names unless the translated name of the real party is just "socialist party" or something like that then I would then prefer to a translated name just to prevent it from looking generic. But due to the displaying of accents problem and that almost all parties have translated names, I will favour consistency over native language naming. So we shall standardise all party names to the English translation.

**Comment by settintotrieste** [comment]
@ARR8 Regarding the localisation encoding, I found this piece of information on it.

"In Vic2 (and NWO) files should always be ANSI encoded. In notepad++ this is easy to fix (under Encoding select ANSI).
Your Republic of China.txt file was UTF-BOM

I corrected and checked it in."

**Comment by ARR8** [comment]
I thought so, too, but it still didn't work. It turns out the character set is ANSI but the encoding is Windows-1252, often mistaken for ANSI. I talked about this in #129, and I think this worked.

So I guess the question is: now that the accent problem is fixed (for most accents) does your answer to the question above change? Currently the parties are still a mix of English and native.

**Comment by settintotrieste** [comment]
Yes, with this new development, I would now prefer to stick to the english translation unless the english translation is just a generic name like "Socialist Party".

**Comment by settintotrieste** [comment]
Migrated the General Discussion thread to "projects" which is a more prominent location.

**Comment by ARR8** [comment]
As a side note, I'm not sure who has edit permissions within projects - I think it might just be those with write access to the master branch.

**Comment by settintotrieste** [comment]
Right, I'm not sure about the edit permissions but I do agree with you on the character limits. Perhaps it would be better if we were to shift the thread back here?

**Comment by ARR8** [comment]
I agree, though I think the culture discussion warrants its own issue

**Comment by settintotrieste** [comment]
Yes, I can't seem to put a post there while on mobile for some inexplicable reason so I'll put my reply here.

I agree with you on the culture colours, they are too close to it each other at this point. A vanilla colour layout would be much better. 

I don't quite understand your second point. Are you referring to assimilation or immigration?

**Comment by ARR8** [comment]
Sorry, assimilation. In vanilla, pops can only immigrate to the New World, and always assimilate. In the mod, pops immigrate anywhere, and assimilate nowhere outside their own culture group. Assimilation should be possible outside the culture group, otherwise assimilation as an old world country doesn't really help you tangibly, as you never get pops large enough for anything useful, and for thematic reasons.

**Comment by settintotrieste** [comment]
Thanks. I wholly agree with your point, this can also tie in with the current decisions that promote or reduce the assimilation rate. Opening up new gameplay features like giving the choice between promoting faster assimilation and risk angering the locals or reduce assimilation but angering the new immigrants. So what we can do is to enable assimilation beyond their own culture group but make the assimilation slow so as to incentivise decisions that promote assimilation.

**Comment by ARR8** [comment]
Right - the reason I haven't brought this up until now is the amount of testing and balancing it'll need, which is probably better saved for a new version.
  Something else we should consider is union cultures: this isn't the Victorian era, and nation-states aren't so prominent anymore. There's something like this already present, with European, Yugoslav, etc. but neither of them really work. Either way, I feel there should be some kind of growth of a national identity in non-nation states like Yugoslavia, Switzerland, African nations, etc. that the player should be trying to encourage.

**Comment by settintotrieste** [comment]
I see. Going forward, I can do the basics first of making such assimilation possible then we can slowly tune the rate over the subsequent CWE versions. 

I like the idea of union cultures and its growth however I'm not too sure how to model in their growth as due to engine limitations as only the primary culture can grow. Perhaps something like a "Pan-Continent/Union" decision to change the primary culture of the nation into the respective union culture, this can then allow the player to promote the rise of union cultures in their nation.

**Comment by settintotrieste** [comment]
87b752a More dynamic assimilation to allow for assimilation based on literacy, culture group, luxury needs fulfilment and employment levels.

**Comment by ARR8** [comment]
Any update on making Vietnamese Christian the primary culture of South Vietnam from feedback? I think it's a good idea personally, have you decided against it?

**Comment by settintotrieste** [comment]
Thank you for the heads up, I completely forgot about this. I am still very much in favour of it, I will do add it in tonight before I forget again.

**Comment by settintotrieste** [comment]
Is there an event/decision to move the capital of Israel from Tel Aviv to Jerusalem?

**Comment by ARR8** [comment]
No, that could be considered for #113. I'm not sure if it should be included, though, since Tel Aviv is the de facto capital and our map is a de facto one. If added, it would have to be after some future event that hasn't yet happened.

**Comment by settintotrieste** [comment]
I think it should be since the question of the capital of Jerusalem is a huge stumbling block to a two state solution and is a major issue in the Arab Israeli conflict.

**Comment by ARR8** [comment]
Currently, Palestine loses cores on Jerusalem if Israel maintains control of it for long enough and navigates all of the events successfully. Essentially, past that point, which I think happens after one of the intifadas, the two-state solution if forced will only include Jerusalem in very rare circumstances.

**Comment by settintotrieste** [comment]
24/6 will be the target date for 1.06. The week before the released will be devoted solely to bug fixing and tuning the historical accuracy of the game flow.

**Comment by settintotrieste** [comment]
@ARR8 May I know your current status on the mod, what will be your focus before 1.06 is released?

**Comment by ARR8** [comment]
Due to things in real life, I'm not sure how much time I'll be able to commit to modding. Let me know if you need anything urgent, but I'm afraid I'll have to be considered inactive for the time being.

**Comment by settintotrieste** [comment]
I see, sure. The core features for 1.06 are done so I'll be able to handle the remaining minor features and testing. Thank you very much for all the help you gave for 1.06!

**Comment by ARR8** [comment]
Thanks for understanding. For what it's worth, I really enjoyed working on it! Let me know if you'd like me to create issues for all the things I had on my "to-do" list, in the event I won't be able to get around to them myself.

**Comment by settintotrieste** [comment]
Sure, that will be great! Please do!

**Comment by Andrettin** [comment]
@ARR8 @settintotrieste The encoding in Victoria II's files is indeed somewhat weird. Sometimes the province history files will break at a certain point, for no apparent reason. It's really quite a weird thing.

For at least one of the problematic files ("2172 - Mexico City.txt"), GitHub read all of its code as one line. Perhaps that's the reason why the file wasn't working properly in-game for me, as I used comments (and if it is being read as one line, the comment will break the rest of the code). Trying to change the file did nothing in that regard, and note I was already using ANSI encoding in Notepad++. Only deleting the file and copying its content to a new file worked.

**Comment by ARR8** [comment]
Sounds like a problem with the line endings. Github tends to store files with Unix-like endings, while Vic2 expects Windows ones. I think git can be configured to favor one over the other, as can npp.

Regardless, you are completely correct, and that's one of the downsides of "old" software like the Vic2 engine. Nothing to be done, sadly.

**Comment by settintotrieste** [comment]
Discussion moved to discord
