### ISSUE TITLE
Bad Reforms

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#125]
One of the best features of NWO in my opinion was the addition of some "bad" political reforms if you reform to the end, in which the last level is actually closer to having no reform at all (e.g. compulsory voting only empowers the rich). This is good for balance reasons, as currently progressive/liberal/socialist parties are undoubtedly the only good ones unless jingoism is needed.
  This can also be another dynamic political factor as in #50, for pops to desire a right-wing government to roll back some reforms.
  Noticeably, more parties can revoke reforms in the mod than in vanilla, but there is no reason to do so.
  This would also encourage right-wing support in countries which transition to a democracy and automatically get all the reforms.

There's no reason why this can't be done for social reforms, as well; for instance, too much welfare could lower productivity and growth, over-developer school policy could actually harm education (for-profit universities, etc.), Western wage and safety standards lower competitiveness with the East, etc.

**Comment by settintotrieste** [comment]
Thanks for raising this issue let me try to address it. 

I personally dislike the idea of having bad political reforms like the ones in NWO as in Victoria there is no horizontal reform selection, only a linear vertical one so I find that it is not appropriate to make the reforms become negative the higher it goes as the linear system would imply that the reforms will go from bad to good as it is the case in vanilla. Furthermore the spirit of the reforms when it is presented in such a way ought to be to be one that strives to make the political system more fair and workable for all. The problems that come from a better political system should be less obvious and definitely not from a simple -10% of something from the reform. For example, having full voting rights/proportional upper house composition means a more fragmented electorate and upper house which then means greater difficulty in passing other reforms and selecting decisions and that is in addition to greater administration costs of having such a complex democracy which will reduce other aspects like admin, social, education spending in poorer nations with potentially devastating consequences like greater corruption, slower literacy growth and rebellion. This I believe is a more than a sufficient cost to having a more perfect political system. Lastly it makes no sense for compulsory voting to bolster the rich as everyone, rich or poor is voting so the rich vote is being diluted rather than strengthened. It should be the opposite instead where poor voting reforms support the rich as there is less oversight over who votes allowing vote rigging and absenteeism.

With regards to social reforms, the same applies as well which is the need to weigh cost vs reward. Yes a good education system can improve higher education levels which can improve productivity but at the same time costs a lot of money to maintain and also leads to decline in pop growth due to the literacy mechanics. Too much welfare, makes the social spending skyrocket affecting ability to balance the budget. I would say that is not always true that better welfare causes lower productivity but it is more of more regulations. So what I will do is to add negative factory throughout effects to the safety regulations reforms and the environmental regulations reforms. Lastly it is often the case that why social welfare reforms are scaled back is due to the monetary costs of maintaining it than anything else. 

I would differ over the view that only those three types of parties are the good ones as there are many important and desirable  decisions that require the other types of parties. Furthermore socialist parties often prevent political reforms from being selected which makes it difficult to get the beneficial effects from those while liberals generally don't support social reforms so it's not easy to get the social reforms.

Ultimately what I strive to do is not make reforms always bad or good like in NWO but rather good or bad depending on the needs of the individual player. And as it stands all the reforms right now have a cost vs reward to them though it's not always apparent from the reform screen. The same goes for ideologies where the best ideology can still be the other ones if there is a need to enact a particular decision or roll back an overly expensive reform.
