### ISSUE TITLE
Factory text fix

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#132]
ilikepie said:

Also, all the factory text needs to be redone. Sometimes the inputs that are shown aren't what actually gives +12.5/+25% upgrades to factory efficiency, so it's impossible to tell ahead of time where to build factories. (For example, the image for "other minerals" and "integrated circuits" is the same, so I built optics factories where there are "other minerals" but didn't get a bonus until I discovered "integrated circuits" factories). Also, a lot of factories don't have any text descriptions at all, but even the ones that do need to be redone to make them more specific so that they say exactly what things you need to get bonuses, and what the inputs are once it is built (since those are sometimes different for some strange reason).

**Comment by ARR8** [comment]
Sometimes this is caused by vanilla text overriding mod text (e.g. Gas becomes Gas Attack). A quick fix for this is editing all text files to add a cwe_ namespace to the beginning of the name for alphabetization. I think I suggested this a while back. Either way, a better fix would be split up the massive text.csv file into more relevant files for organization.

**Comment by settintotrieste** [comment]
Yes, this is a good idea.

**Comment by settintotrieste** [comment]
I'm thinking of doing a trade goods graphical update and relocalisation to address this problem.

**Comment by ARR8** [comment]
I agree - I've noted the icon issue in #108. Ultimately, though, we should probably have a discussion about whether to even keep all the trade goods, especially since, by the time the late-game ones are unlocked, there's usually no room to build their factories, and the AI is incapable of it. Plus, they're combinations of other goods which I frankly don't understand.

I get the impression NWO was trying to simulate service-based economies, but that doesn't need new trade goods and can just be based on clerks replacing workers in existing factories IMO.

**Comment by settintotrieste** [comment]
Sure, though I am hesitant about removing goods due to the risk of needing massive re-editing and rebalancing of the economy.

Yes, I agree with you. That's why I've made it so that in CWE, the artisans serve as factory replacements rather than a niche industry.

**Comment by settintotrieste** [comment]
I've given up on making factory descriptions as its too much work. Factory names were however cleaned up a bit for 1.12
