### ISSUE TITLE
Starting population demographics

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#133]
ilikepie:

China also doesn't have the best growth. They only have 671 mil in 1977 while India is now at 1.13 billion, but historically in 1975 India had 618 million, and China had 920 million. Part of it might be that India can get "family values" which gives +0.2% popgrowth, but Communist China can't (I don't know what the requirements are, maybe they can theoretically).

Also in 1950 (I had to let the game go that far to get India and China united), India has 491 million total population while China has 544 million. In real life China had 562 million and India only had 370 million, so that is a huge boost to India, combined with not having "family values"
https://en.wikipedia.org/wiki/List_...en_the_years_1950_and_1980_.28in_thousands.29

ilikepie:

I think the main problem is the initial inaccurate population count for India. India has about 470 million at game start. 470-340(irl 1946) is a 130 million increase over the historical statistics. It starts with even more population than India had in 1950 (369 million), or in1960 (445 million): https://en.wikipedia.org/wiki/List_...en_the_years_1950_and_1980_.28in_thousands.29

So India is basically getting 15-20 years of population growth for free, which at the start of the game gives a huuuuge boost to their later figures. The main problem is that the initial population is too high by 130 million, but I don't know if the population should be reduced in just the Raj or in India (excluding Pakistan/Bangladesh) as a whole. I think when the 1946 bookmark was made (I don't know the history of the NWO mod), that someone made a mistake in allocating the Indian population, and gave Dominion India(excluding Pakistan and Bangladesh) 358 million, when the entirety of India (including the minor states) should have been around 340 million. So they meant to give all of India 358 million total, but accidentally gave it to just the Raj (excluding Pakistan and Bangladesh), thus inflating the total population by 130 million.

Did CWE change any population statistics or were the 1946 stats all made by the NWO mod maker?

**Comment by settintotrieste** [comment]
As I do not have a population generator, it will be extremely difficult for me to alter the pop levels of all the provinces of the entire Indian subcontinent to match historical levels.

**Comment by ARR8** [comment]
The population demographics throughout the world have problems. One example is the lack of minority pops except in some very large cities; I mentioned the lack of Jewish pops in #113, but all minorities are affected. I think this is due to NWO's policy for removing all populations unless they were at least a third of the province population. I personally don't think this was worth it, and removes the whole assimilation aspect to the game.

**Comment by settintotrieste** [comment]
I agree, the NWO setup is too inadequete. This is something that we will have to fix.

**Comment by ARR8** [comment]
Some relevant threads:
  http://oldforum.paradoxplaza.com/forum/showthread.php?496441-ProvinceOwnership-and-POPAdjuster-tools - performs batch operations on pops across many provinces, could be useful for simply shrinking the population of India
  https://forum.paradoxplaza.com/forum/index.php?threads/pop-resizer-utility.608224/ - resizes pops based on starting country, could still resize Raj population incl. Pakistan
  https://forum.paradoxplaza.com/forum/index.php?threads/victoria-2-pop-maker-utility.580399/ - generates populations for states using a total and weights of provinces and types, could be useful for generating appropriate minorities

I haven't managed to get the first two to work. Assuming you can't either, the third tool could still save some time by allowing state-by-state generation instead of province-by-province. Sadly, It looks like the Clausewitz Scenario Editor doesn't have pop options.

**Comment by settintotrieste** [comment]
Great work on the Indian population issue and thank you very much for the pop generator links! I will tinker around to see what can be done with them to modify the population of other nations.

**Comment by ARR8** [comment]
Sure - I managed to get no. 1 working, you just have to rename the pop folder to 1836.1.1 for it to run then back to 1946.1.1

**Comment by ARR8** [comment]
Just noticed all Germans are catholic. That should definitely be fixed.

**Comment by settintotrieste** [comment]
Pop growth was redone late 2020 to early 2021. Pop demographics for some nations were also improved
