### ISSUE TITLE
Check level of Soviet control over Eastern Europe

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#140]
[/u/\_\_Rhand\_\_ said:](https://www.reddit.com/r/paradoxplaza/comments/684ytj/vic2_cwe_mod_how_to_know_level_of_soviet_control/)

> Was playing as the champion of the free world, America, in CWE 1946 start.
> 
> As I understand it, the Soviet Union weakens every time it loses a Warsaw Pact member.
> 
> So to accomplish this, I used a series of fast wars. I would use tanks and bombers to launch a series of assaults on Soviet infantry-heavy armies, then after gaining ~40 warscore I would peace in exchange for a puppet release.
> 
> It's now 1986 and I've freed the entire Warsaw Pact.
> 
> -----------------
> NWO lets you view the level of Soviet Control over Europe. Is it possible to do the same in CWE? How do I know how close the Soviet Union is to falling? Is its fall even guaranteed if I destroy the Warsaw Pact?

**Comment by settintotrieste** [comment]
Technically there is no way of checking the level of soviet control over Eastern Europe because there are no levels. The control over Eastern Europe events were remnants from NWO.

Personally, I find that it is better if the player does not know how close the USSR is to falling nor be able to condense complicated factors that can cause a collapse into a simple binary numbers like in NWO as it would make the game less realistic. Part of the Cold War was uncertainty, both sides believed that their rivial' collapse was inconceivable and neigh impossible except due to WW3 and Gorbachev's reforms. Part of the challenge for the player is to anticipate when the USSR is going to fall. 

Technically destroying the eastern bloc should not cause the collapse of the USSR as it collapse was often attributed to a loss of national unity and commitment to the communist ideology and destroying it would definitely have rallied the USSR together and reinforced the hatred of the capitalist imperialists to fight against the threat to their security. This would have made he USSR adopt a position like in WW2 where the USSR actually became stronger.
