### ISSUE TITLE
Portuguese colonies in India

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#146]
BPEMASTER:

Is there any way for you to add the portuguese Colonies of Daman, Diu and Dadra in India?

**Comment by settintotrieste** [comment]
I'll try as I'm not sure if those provinces exist in the game which might mean that I need to add provinces for them which I don't know how to do.

**Comment by ARR8** [comment]
Dara is probably too small to add and has no population statistics of its own, so that's definitely out.

The other two are very small with very small populations. I don't want to do the NWO thing of making provinces too small to click on, so here's what we can do:

- Make large and separate Daman and Diu
- Make a large Daman and Diu as one province, with state to be figured out later
- Add them as nonadjacent exclaves of Goa with pops added to Goa
- Drop the whole thing

The first two would make disproportionate provinces, and the third one may confuse players who send a move order to those provinces and end up marching into Goa.

Either way, I think the third option is the best - I'd like to hear what you think.

**Comment by settintotrieste** [comment]
I made this decision to post this issue without knowing about the colonies. With this information I would now gravitate towards saying that they are far too peripheral to create a meaningful geographical feature out it so I am leaning towards no.4. However as I don't quite understand what is no.3 we could go still ahead with it.

**Comment by ARR8** [comment]
Basically, no 3 is just changing some pixels near where these colonies would be and making them part of the Goa province instead of whatever province they were a part of. A lot of minor islands work this way in the mod currently and in vanilla.

**Comment by settintotrieste** [comment]
Sure, this is a good way to represent those tiny colonies.
