### ISSUE TITLE
1992 General Tweaks

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#169]
At the moment immigration is too high in 1992 due to all Indian states being states which causes the 1992 start to be laggy. The Indian states are also problematic as it makes their economy grow far too fast. A 1946 state setup for India would be ideal to remove these problems.

**Comment by ARR8** [comment]
Currently, it is impossible to go from the 1946 India setup to the 1992 India setup because many states are not of the primary culture. I propose keeping at least the non-Indian-cultured states as colonies in 1992. I'm not sure right now how many of those there are and how big an effect that would have, but it's a good baseline that should help somewhat.

**Comment by settintotrieste** [comment]
I like your solution it's a good way to balance gameplay versus reality. If you can please go ahead with it.

**Comment by ARR8** [comment]
One thing I noticed - we set Madras as a state from the start in #21, but it's not Indian culture and I've made it a colony in 1992. Should we change one of the start dates to match the other?

**Comment by settintotrieste** [comment]
Yes, please match the 1992 setup to the 1946 setup. I need the 1946 setup to remain as it is to ensure that India's economic growth is not overpowered.

**Comment by ARR8** [comment]
Sure, and I'll make an Indian cultured state into a colony to keep the same amount

**Comment by settintotrieste** [comment]
Thanks!
