### ISSUE TITLE
Translation of Italian Parties names

### ISSUE THREAD

**Issue by KeyboardMonkey95** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#241]
Would you like me to translate the Italian party names (which i originally made in Italian) to English?

**Comment by settintotrieste** [comment]
Sure, that will be great!

**Comment by ARR8** [comment]
Correct me if I'm wrong, @settintotrieste - if the translation is a generic name, such as "Socialist Party," then the Italian name would be better left as-is.

**Comment by settintotrieste** [comment]
Thanks for alerting me to this ARR8. In this case, we shall leave the party names untranslated.

**Comment by settintotrieste** [comment]
Yes that would be correct.

**Comment by KeyboardMonkey95** [comment]
What if the translation would be "Italian Socialist Party"?

**Comment by ARR8** [comment]
I believe we generally take out the country name to stay below the soft length limit, e.g. 5a5df87

Since the font we use is variable-length, it's difficult to see the length limit (overflowing the politics or province box) without checking in-game, so, even if it might fit, we take it out as a precaution. The two in the example were ones that didn't fit.

If you want to check to see that it's not too long, you may leave it in, and then translated or not at your discretion.

**Comment by KeyboardMonkey95** [comment]
Ok, i'll make sure they aren't too long.
