### ISSUE TITLE
'non-conflict' regions which are divided between countries

### ISSUE THREAD

**Issue by DutchDylan** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#260]
I noticed some regions are split up between countries, but have no conflicting cores.
For example:
-Schleswig, Denmark-Germany
-Various Germany-Poland regions
-Various Poland-Soviet/Belarus/Ukraine regions
-Inner/post-breakup Soviet regions (Rostov Ukraine, central-asian regions for 'stan' countries)
-Kashgar, Soviet/Tajikistan-China (justified by a breakway state, chinas claim greater)
-Istria, Italy-Yugoslavia/Slovenia, Slovenia/Croatia
-A couple more minor ones

Some of these are left over from Vanilla while others are intended for breakaway state crisis to function. But in general having these regions split up causes inefficiency for factories and employment, and may cause problems when forming superstates sicne they combine the regions again, potentially deleting factories if over the 8 limit and causing unemploument due to deleted factories.

I'm in favour of these regions being combined and/or beign resdesigned so they better fit the national bordes of the countries, I couldn't find any issue related to this so I'm not sure what the general opinion on this is.

**Comment by settintotrieste** [comment]
As far as I can tell, the overall impact of this on the game is relatively minimal so addressing this will be of a very low priority. 

Redesign of regions is definitely something I'm quite against as often introduces more problems elsewhere. An example of this would be the NWO mod which attempted and failed rather catastrophically in trying to completely redesign regions along the lines you have proposed as it led to some countries becoming underpowered/overpowered due to the change in the number of states and therefore factories each country can have which was in addition to new bugs being introduced as some events now referenced the wrong state ID.

**Comment by DutchDylan** [comment]
Ah I see, I definitely get what you mean with the problems it can bring and the redesign which NWO had attempted. 
The impact is indeed minimal but I hope in the future when CWE gets even more polished we can put region redesigns on the agenda, I agree that what we have now functions well enough.

**Comment by settintotrieste** [comment]
Since 2017, some states have been edited to address the problems highlighted here.
