### ISSUE TITLE
Support for insurgent movements in other countries

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#263]
Hello. I suggest making it possible for the Great and Secondary Powers to support the rebel movements in other countries.

For example, Saudi Arabia or Turkey will be able to support the revolution in Syria, which as a result will break out and replace the government in the country.

Thus it is possible to make so that the Superpower could stop these actions that for example there was no situation at which for example Russia simply arranges the power in the Baltic States or for example suddenly Germany on what that logic changes the power in Sweden, by a creation of revolution there.

Or how else can we limit the support of revolutions.
There is one more option - To allow only superpowers to support the revolution, at first glance it is logical, but still, it is better for me to let all the Great and Secondary Powers

**Comment by settintotrieste** [comment]
A large part of this is already in the mod since v1.05

For superpowers, they can set the level of guerilla support in the spherelings of the rival superpower to promote the rise of rebels.

For any other country neighbouring a country with an active rebellion, they can choose to either support the rebels or the government and having a country supporting each side cause the chaos in the country to escalate that can potentially draw in the superpowers to arbitrate.

Unfortunately due to game limitations it is not possible to code support for insurgent movements beyond what is already in the mod.
