### ISSUE TITLE
Casus belli on installing friendly Democratic regime

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#264]
Hello. Why is it not possible to install friendly Democratic Regime for the United States? Is it dependent on ruling party? 

If this is so then why not make it possible for all parties? And why can they establish a friendly dictatorial regime?

Also, I propose to add the Casus Belli to the establishment of a friendly Democratic regime for such countries as Great Britain, France and Turkey.

Similarly, Saudi Arabia does not have casus belli to establish a friendly regime. It would not be bad if Saudi Arabia had the opportunity to establish the "Muslim Brotherhood" in the power in other countries (For example)

**Comment by settintotrieste** [comment]
Yes, you need to have a jingoist ruling party and great power status in order to install democracy. i do not intend for all parties to be able to install democracy as it will only mean that the AI will start waging too many wars and is unrealistic as a pacifist or even a pro military government in real life wouldn't want to go to the extent of waging war to install a friendly government.

They can't due to thematic reasons. A democratic nation in the Cold War to modern era will want to install democracies as far as possible, maybe sometimes flawed democracies but definitely not dictatorships. However they may give support to a dictatorship for strategic reasons but they did not create the dictatorship in the first place.

This is because Saudi Arabia is not a great power. The friendly government mechanic involves sphering the country which needs great power status. However you can still puppet those nations. That also serves as a way to install friendly governments.

**Comment by samwoodzadrot** [comment]
Hmm ... Okay. But still about the US, as for me they should be able to establish a friendly Democratic regime and not be able to establish a dictatorship.
