### ISSUE TITLE
Chinese Sphere of Influence

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#291]
If China is the second superpower in the game then by 2000 the China sphere of influence includes such countries as Portugal, Bulgaria, Armenia, Georgia, Kazakhstan and sometimes even more.

Please fix it.

BUT:
When I made the second Superpower Russia, there were no such problems. The only thing is that Russia at some point took North Korea into its sphere, but this is easily corrected if initially to make North Korea a Chinese sphere of influence.

So I suggest making Russia the second Superpower in the 1992 scenario. I think it's better suited. In my understanding, there is only one superpower in the world (the USA), but if you determine what the second is, in my opinion, Russia is more suited to the notion of a "superpower" than China. The superpower is a country that can project its influence around the world, China is still engaged in its region while Russia, for example, directly participates in the events in Syria.

**Comment by settintotrieste** [comment]
1. If this is in the 1992 start date, this is often due to the China AI that is choosing to sphere those countries. The AI is un-moddable so there is nothing that I can do about it. On the other hand, such a situation will take longer for the China AI as the Russian AI has already previously sphered those countries during the Cold War.

A solution for this is to pre program the infulence levels of the countries in the 1992 start so that it will take longer for China to sphere them if the AI wants to sphere them.

I don't believe that making Russia a rank 2 nation after the end of the Cold War is historically accurate as in the following 10 years after the dissolution of the USSR, Russia was internationally recognised as a crippled rump state that was reduced to a mere regional power status unlike China which was viewed to be a growing regional power on the verge of becoming a global power in the 1990s. Russia's return to global power status only started around 2014 according to international analysts.
