### ISSUE TITLE
Roc keeping the mainland in 1946

### ISSUE THREAD

**Issue by DullishCrab94** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#313]
Sorry if im spamming but i was wondering if you could have the roc have a 50/50 chance of winning the Civil war and unifying china instead of it always being the prc so it can have a little alternate history and not always be historical

**Comment by what-am-i-doing** [comment]
Currently ROC loses the mainland if PRC occupies 35% or more of their provinces. If the ROC is able to prevent that from happening, they can win. Extremely rare, but it can happen. The main reason PRC generally wins is because they start out with much better military tech. Evening out the military tech advantage a bit would probably help.
