### ISSUE TITLE
A few issues with the ussr

### ISSUE THREAD

**Issue by ghost** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#350]
played the latest (nightly) version
1946 bookmark

- for some reason some provinces in north caucasus and central asia are not states at the very beginning of the game. Is this intended?
- shouldn't the people's republic of china be in ussr's sphere of influence at the beginning of the game?
- soviet industry seems way too small at the beginning of the game: (the maps are dated way after 1946 but I could not find a better source, sorry)
http://images.nationmaster.com/images/motw/commonwealth/ussr_metal_1974.jpg
http://images.nationmaster.com/images/motw/commonwealth/soviet_machine_82.jpg
http://images.nationmaster.com/images/motw/commonwealth/soviet_pet_refin_82.jpg
http://images.nationmaster.com/images/motw/commonwealth/soviet_pet_deposit_82.jpg

Also a bonus issue:
Communist Greece has no army at the beginning of the game. Is this normal?

**Comment by settintotrieste** [comment]
Thanks for your feedback!

1. No, I will have to look into it.

2. Yes but if I remember correctly the sphereing is added by an event as the USSR took a hands off approach initially in the Chinese civil war.

3. This is intentional so that the AI can build factories according to world demand so as to maximise the long term economic stability of the USSR.

4. Yes as the communists will get a few divisions when the mobilise after 2 Jan 1946

**Comment by Tebix** [comment]
There is are more problems, you don't get the casus belli when the USSR breaks up

**Comment by settintotrieste** [comment]
I've no intention of adding a CB for Russia to reclaim the former Soviet lands as part of the treaty that dissolved the USSR was an intention of the former SSRs to withdraw from the Soviet Union.
