### ISSUE TITLE
Guerrilla Warfare

### ISSUE THREAD

**Issue by naoisemct** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#373]
I think an "initiate guerrilla warfare" decision for countries being invaded would reflect the asymmetrical nature of modern warfare, especially in places in the Central Asia and the Middle East. I would propose a decision which has tax and infamy penalties for either massive militancy increases or an organisation and regain hit in occupied provinces. I don't know if occupied provinces can rebel so I'm not sure if this is possible, but it would reflect insurgencies in occupied lands..

**Comment by settintotrieste** [comment]
Part of this has been implemented in the 'Support separatist movements' decision.

**Comment by Devin616** [comment]
maybe communist/socialist or theocratic governments could use a guerilla warfare decision when ivaded that would create small guerilla troops, these troops would high morale reinforce and organise faster and move faster and would attack bonuses, at the cost of the fact that they would take high casualties and since they are reinforcing and reorganizing quickly they would drain your population quickly and hurt your economy, perhaps using guerilla troops could also increase militancy and consciousness (the reasoning being people realize that fighting a larger army is totally possible and might use that realization to start rebel movements against their government) so despite the fact that they are OP, players would be hesitant to use them unless they are desperate because it will hurt them in the long run.

**Comment by settintotrieste** [comment]
I will look into he partisan system HPM used in its latest versiom

**Comment by settintotrieste** [comment]
It has proven impossible to spawn rebels through decisions and the partisan system in HPM will create a lot of event spam. To apply a modifier to occupied provinces to add militancy is also not good because it will trigger other rebels to overthrow the existing government instead of the occupiers.
