### ISSUE TITLE
many RGOs empty in the first two decades

### ISSUE THREAD

**Issue by laingawbl** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#429]
I have noticed that certain RGOs, like Grain, will be totally empty (0 workers) between the '40s and '70s, until resource efficiency techs are researched. There will be large numbers of unemployed farmers and labourers, but none of them will be working the RGO.

I do know RGO unemployment is a well-known problem with base Vicky. But if factory profitability can be rebalanced, do you think it would be somehow possible to rebalance the resource market into ensuring that RGOs are always worked to _some_ extent? I don't think it's right that _e.g._ as West Germany in 1968, and lots of starving nuclear plants, I should have an Other Metals RGO with nobody working it.

I have two guesses as to why this happens:
- The nonzero minimum subsidies mean that most low-value RGO workers make more from unemployment than they could working the RGO. I think this can sometimes happen in base Vicky with higher UB reforms. However, I tested this by setting Social spending to 0%, and it doesn't make pops start working the resource.
- Some countries are producing so much of a resource that they flood the market, making other countries' RGOs unprofitable (as happens to India's Dye RGOs in HFM). But, because of sphere/GP/this mod's bloc mechanics, nobody except maybe the US and USSR can buy them. My limited knowledge of Vicky's resource market is that it's one of the more kludgey areas of the game code. Most Coal RGOs in my current save seem to be empty, except for a few giant ones in China and one in Kattowitz, which must be contributing most of the global supply.

I should add that this doesn't really affect gameplay if you don't look too closely - you can still get a healthy industrial score, and satisfy most pop needs - but most of the factories will be around 0 employment and producing nothing at all!

**Comment by settintotrieste** [comment]
The rgo problem is due to a hardcoded bug made worse by large spheres at the start of the game. There is plenty of demand but due to the bug, it’s not reflected properly outside of one’s sphere.
https://www.reddit.com/r/victoria2/comments/cdujhn/a_complete_understanding_of_victoria_2s_markets/

It’s difficult to balance RGO levels because a scarcity of RGOs in the early game will mean an acute scarcity past 1980 when industrial scores start increasing exponentially. Modifiers can help but it tends to go out of hand quickly because it only increases by a fraction. Example, changing the default rgo output from 1 to 5 requires a 500% modifier.

RGOs don’t have profitability values to edit as well making it difficult to balance as it would be determined solely by supply and demand which is impossible to reliably calculate in game.

**Comment by settintotrieste** [comment]
A stop gap  solution has been found by making the fire rate of RGO = 0 which means that RGOs will hire in accordance with increasing demand but won’t fire when there is high supply.
