### ISSUE TITLE
Small economic overhaul

### ISSUE THREAD

**Issue by Mitusonator** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#431]
Hi I made a submod that implements some changes to economy (and some fixes to few other things), I posted about it in paradox forum but I know that you don't visit it very often. 
Maybe you could consider implementing it into the main mod.
This version is _two commits behind the github version, so if you decide to try it out and implement it you would have to compatch them_ **(nevermind already compatched it)**, or you can give me your permition to commit it myself.
If you don't like some changes you don't have to implement all of them but be coutious not to delete something vital to economic balance. 
If you would like to discuss my changes in more detail I am totally open for talk.
With high regards :),
Mitusonator,

**Comment by Mitusonator** [comment]
Oh and I did some more small changes than in the version on forum page, so I would have to upload it again, of course if you want.

**Comment by settintotrieste** [comment]
I appreciate your work on the economy however I will need to reject the changes due to these issues:

1. Raw resources being tagged as a "credit" resource would mean that it will not appear on the trade goods screen which makes it troublesome to analyse the economy for players. It would also lead to excessive money gain for all countries and pops which increases the chance of a stack overflow error from the 1980s onwards.

2. Factory production and pop consumption levels are much higher than in the current version. Making the GOLD_TO_CASH_RATE = 0.00 will mean that the credit resource is useless which affects quite a few features in the mod.

3. FACTORY_PAYCHECKS_LEFTOVER_FACTOR = 0.95 is too high. This is the cause of many mysterious crashes starting from 1970 onwards.

**Comment by Mitusonator** [comment]
This is unfortunate but understandable ;)

**Comment by settintotrieste** [comment]
I noticed that you changed one value in defines to prevent firing of RGO workers which helps a lot with the unemployment issue. I've added that to the current mod.
