### ISSUE TITLE
Populists in Brazil

### ISSUE THREAD

**Issue by MillanAstray** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#438]
I think I already commented that a while ago, but besides your great work in this mod this specific subject still got problems. The populists in Brazil are not getting the relevance that they get in real life, that's unrealistic. 
The political legacy of Vargas really movemented and polarized the political scenario in Brazil, and the coup in 64 was aggainst a nationalist populist heir of Vargas, João Goulart. Unfortunately in game conservative and liberal parties always get in power and are much more numerous in the upperhouse. If that was the scenario the coup just wouldn't happen.  

The political scenario in Brazil until 64 must be polarized between the populists/left nationalists with minor support of communists and socialists, against the conservative and liberal with US support.  And the resistance against the coup in 64 would certain lead to a civil war. That could be a important event in game, with the possibilities of US intervention, and USSR support for the populist side. 

João Goulart: https://en.wikipedia.org/wiki/Jo%C3%A3o_Goulart

64 coup: https://en.wikipedia.org/wiki/1964_Brazilian_coup_d%27%C3%A9tat

Operation Brother Sam, the possibilitie of US intervention in case of resistance: https://en.wikipedia.org/wiki/1964_Brazilian_coup_d%27%C3%A9tat#US_involvement

A lot of brazilians love your mod, would be great that we get more flavour. Thanks.

**Comment by Otto-Fon** [comment]
I think the meaning of the "populist" idelogy in the game is to present the far right and not Latin American populism. Since every country in the world has this idelogy and there was no such populism in the Philippines or the USSR. So to better represent what you are saying, it is better to use the Nationalist idelogy of the game but with the parties with names and policies that represent this Latin populism more, be it more leftist like Janio Quadros in Brazil or the right with Juan Perón in Argentina.

**Comment by settintotrieste** [comment]
Mod development has stopped and so all outstanding issues will be closed.
