### ISSUE TITLE
Superstates should vassalize member nations, not just form a single country

### ISSUE THREAD

**Issue by AIndoria** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#439]
Ideally how it would work is like the Soviet Bloc with member nations being a vassal/puppet state, so you can still be part of say, the EU and still play as France. That by itself would make it more realistic than just having a big-ass blob on the map.

**Comment by Bismarckingit** [comment]
the first problem here is that major powers, by definition, cannot be vassals. the point is also that it steadily federalizes over the course of the reforms you pass. i think it's a little more realistic to make such a superstate incredibly unstable once it forms, rather than make it decentralized, when centralizing was the entire point of the reforms.

**Comment by settintotrieste** [comment]
The ultimate goal of the EU is to unite and integrate all member states under a single political administration hence it should be represented as a single country rather than a federation of puppets
