### ISSUE TITLE
Mladorossi

### ISSUE THREAD

**Issue by CipKac** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#485]
More than a little silly, I know, but I thought someone would like to see what would the consequences be for a restored monarchy on Russia. I certainly would like to see an alt hist on that regard. And hell, it has a slightly higher chance than a straight up restored Russian Empire, given that Alexander Kazembek had ties with the Soviet consulate and OGPU.

It has about as much chance as China has of restoring the monarchy like the decision allows, that's for sure.

I believe the mod start date is 46 while the group was dissolved right after the end of WW2 (in 45?), but eh.

**Comment by settintotrieste** [comment]
Are there any modern calls for a restoration of the monarchy?

**Comment by zassuen** [comment]
Going by wikipedia's page on monarchism, about 28% of the population approve of a restoration, there's also a russian monarchist party, and I know there's a lot of support in the orthodox church also.

**Comment by zassuen** [comment]
Hey, so, I was thinking about a initial event for the USSR relating to the abolishment of the Union of Mladorossi a few years prior. There would be three options. The first would be to abolish it as historical, which would grant some prestige and maybe lower militancy a bit but nothing more. The second would be to keep it going but not allow them to return to the soviet union, which grants nothing. And the third would be to readmit the emigrés back into the Soviet Union.

imo the third option should cause an increase in militancy and consciousness, as well as a prestige decrease, and is only an option due to the conciliating stance of the party and it's founder's ties to the soviets (https://en.wikipedia.org/wiki/Alexander_Lvovich_Kazembek, https://en.wikipedia.org/wiki/Mladorossi#Fall_of_the_Mladorossi). It would set a flag for much later on, I think the August Coup or the 1993 Constitutional Crisis would be great.

From there you could pretty much go wild.

Alternativelly, you could put in a decision for if a traditionalist party assumes power in post-soviet Russia.

**Comment by settintotrieste** [comment]
Okay, I’ve done some research on this and it doesn’t look feasible. The Mladorossi was effectively non-existent by 1946 and there’s also a problem with who should be emperor. The execution of the Tsar and his immediate family and the subsequent deaths of all the royals in the White army meant that there was nobody famous enough to become king. Moreover there has been too much vagueness as to who is the current pretender to the throne after the war.
