### ISSUE TITLE
German grain issue.

### ISSUE THREAD

**Issue by mpristave** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#543]
For some reason as DDR Germany poor gets 0% life needs and they are looking to buy just grain. If you end up having enough stockpile for everyone they still do not gain grain.

This resolved itself once I got unification, until I quit the game and loaded the save where it returned.

**Comment by cecillia-liebkne** [comment]
I would assume it to be two things: first, the infamous sphere bug that can prevent pops from being paid, and second, the same issue as 2613e718c26af39da8eaf073051e6bf0975c7d1f, in which the massive import cost that piles up prevents them from buying much of anything, especially pops who run on a much smaller-scale budget. Communist countries in general get stuck with the autarky modifier due to the Soviet Union, while their government type do not get to be exempt from corruption modifiers unlike their democratic AI counterparts.

2613e718c26af39da8eaf073051e6bf0975c7d1f is already a silly band-aid solution to the problem though, and the same goes for adding another exemption for communist AIs to corruption modifiers- which would essentially make it solely a player debuff at that point. Reduce the numbers so they do not add up to such a large amount perhaps.

**Comment by mpristave** [comment]
Well what's weird is i'm in the 90s now  and I haven't had autarky for a while and it still is like this, and they are getting 0% of needs. I also have 0% tariff right now and I took a bunch of decisions that boosted poor income. 

Basically it also says  "some good not available on the market" and lists grain as the good.

**Comment by mpristave** [comment]
Changed to being a republic and played up to 2003 and it still was the same with this.

**Comment by settintotrieste** [comment]
I reduced the import costs for the corruption and autarky modifiers. Does it improve the grain issue?

**Comment by mpristave** [comment]
> I reduced the import costs for the corruption and autarky modifiers. Does it improve the grain issue?

I'll check it when i get home tonight.

What's odd though is I wasn't using autarky and this was going on, but i'll have to check corruption i do not believe it is high. The citizens had money to buy grain but it was saying it wasn't available on the market, not that they couldn't afford, when you looked for reasons why they couldn't acquire.

**Comment by cecillia-liebkne** [comment]
That is extremely strange. Are you in a sphere? If so, when you test things, could you also check if the problem persists even after you remove yourself from it? Could you also try switching to other tags, communist or otherwise, and see if they are also having the same issue? If you can find a pattern amongst which tags have the issue or not, it would help narrow down why this is happening.

**Comment by mpristave** [comment]
So I haven't had time to come back until now. I installed the updated version, it changed nothing.

I am not in a sphere or anything like this. 

I also started a new game and went communist as another country this isn't wasn't there. 

I loaded the game from 1950 where I saved before the SU can form the DDR and I did it again and it seems it doesn't have this issue for now.

**Comment by mpristave** [comment]
I think I might have found the origin to this problem.

There is an event about the reconstruction of germany. As the soviet union I took the allow some rebuilding. Immediately after that my poor were unable to buy grain.

I reloaded and picked the other option and it was fine.

I loaded up the event again and picked the rebuild event and it happened once again.

**Comment by settintotrieste** [comment]
Do you happen to have the event name or id?

**Comment by mpristave** [comment]
8024020 I think is the event.

**Comment by settintotrieste** [comment]
I've done another change, does it fix the problem?
