### ISSUE TITLE
Modelling nuclear strikes more finely using rads/hr exposure

### ISSUE THREAD

**Issue by laingawbl** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#558]
I have a little patch on my local version of CWE that replaces the `nuke_*` modifiers (low, med and high) with modifiers representing various levels of biological radiation exposure. The idea being that a nuclear attack does damage in three ways:
1. Initial thermal + overpressure, which is already modelled by the initial `nuke_attack` events and seems pretty good.
2. Ambient radiation, which follows a fairly well described curve based on the relative rates of decay of various fission products of nuclear material.
3. Persistent "[hot particles](https://en.wikipedia.org/wiki/Hot_particle)" in the soil which may cause problems in agriculture for years to come, because they're not dangerous externally, but fatal if you ingest one.

The last two effects are modelled right now by the flat `nuke_low`/`_med`/`_high` modifiers, which are kind of inaccurate because they apply a flat, non-decaying malus to the province which lasts for a long, long time.

- The radiation modifiers follow the 7-10 rule:
![7-10-rule](https://user-images.githubusercontent.com/14956219/82007410-00375400-961f-11ea-85d9-15074690daf2.jpg)
and stack on top of each other, so the most severe disappears after 2 days, the next after 14 days, then 3 months, 22 months, etc. These go away after about 12 years, whereas e.g. `nuke_high` persists for 50 years. They are all identifed in the form of "xxx rad/hour exposure" to give some human bearing on what the effect is actually doing.

- The hot particle modifier sticks around for 40 years, but it only affects tax and farm RGO efficiency, not pop growth. The idea being that it doesn't kill anyone directly, but a lot of the produce you grow might have to be screened for radiation and chucked out. And also, IDK, you can't go collect taxes in an irradiated field, tax efficiency seems like the standard catch-all malus in CWE.

Does this sound like a good model and a good addition to the mod? One drawback I see with my patch is that I model the fallout curve by applying all the modifiers at once to a province and setting lifetimes of various lengths on them, because that's simpler than constantly firing events replacing one fallout level with its successor lower level. But right after a nuke, that means every province has a bunch of radiation modifiers of the form "500 rad/hr, 50 rad/hr, 5 rad/hr, ..."

**Comment by settintotrieste** [comment]
This is an interesting idea however I think it’s little too complex. Also, the current setup does kind of already simulates the different stages of a nuke attack because the nuke event reduces pop levels immediately which simulates 1 and there’s a nuke fallout modifier via a subsequent event that applies a much lower malus that sticks around for quite a while and can spread to neighbouring countries. 

The nuke high etc modifiers simulate the social-economic impact of a nuked city rather than just radiation deaths hence the non decaying malus. what is likely post nuclear attack is that the city pops will start dying en mass due to disease and poor sanitation while those who survive will flee to the countrysides and never come back. The city will then become an empty shell after a while and remain so for a long time. The modifiers do this by applying a flat malus over a long period of time.
