### ISSUE TITLE
Batustans exploit

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#56]
Takethatvonhapsburgs said:

I noticed while playing as South Africa, you can release all of your substates for the lowered infamy and instantly annex them with the "End of Bantustans" decision. This seems like it can be taken advantage of easily. I figured you might like to know.

The solution I will pursue:

I will make the Batustans non releasable from the release nation tab.

**Comment by ARR8** [comment]
In my new game, South Africa turned back into a dictatorship, released the Bantustans a second time, was turned back into a democracy, and then couldn't end the Bantustans again. Is it possible to undo the flag on the decision and use the original solution? Or was there a problem with that one?

Alternatively, we could do the same thing for the create Bantustans decision and allow it only once, but that seems too limiting, especially since a renewed dictatorship would probably pursue the policies of the old one.

**Comment by settintotrieste** [comment]
Thanks for the feedback. There was a problem with the previous one as it did not allow the Batustans to be formed. I think the fix would be to remove the Batustans flag when the Batustans are formed.

**Comment by ARR8** [comment]
That's a good fix, I should have thought of it! I think that solves any outstanding issues to do with the Bantustans.
