### ISSUE TITLE
Implement realigning elections or other party shifts

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#57]
https://en.wikipedia.org/wiki/Realigning_election

There should be a way of generating likely party realignments based on pop ideologies or cycling through historical ones. This should also tie in to national values #54 somehow and possibly #51. I remember in NWO there were events each election that gave it a category, like contentious, orderly, wartime, etc. that influenced how pops would vote in that election. Were those in the mod, I would propose adding a new one along those lines that changed the NV at the end or motivate enough pops to side with an ideology that it would change by decision.
  Incidentally, were those removed intentionally, or did those disappear back in NWO? Are there any plans to put election events back?

**Comment by settintotrieste** [comment]
Yes they were removed intentionally and as it stands I have no intention of re implementing it. I don't like election events to be honest because they are rather spammy and tend to give too much power to the player to shape the election. I think a separate, less intrusive system to push the pops towards the different ideologies that would then allow the national value to be changed would be a better solution.

This can be done via editing the ideologies and issues of the pops in the file for craftsmen, farmers etc to correspond to what they would align to in a war, civil war, terrorist strike situation without a need for a steady stream of election spam every 4 years.

**Comment by EmperorRAG** [comment]
Your addition to the pop ideologies makes the game crash when looking at the factors in-game that influence them. This is due to some of the modifiers having has_country_modifier in them which isn't allowed in the pop_scopes. All that needs to be done to fix them would be to change the has_country_modifier to has _country_flag.

**Comment by settintotrieste** [comment]
Alright
