### ISSUE TITLE
Lack of worldwide urbanization

### ISSUE THREAD

**Issue by Sillken** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#775]
Farmers and labourers always seem to end up overrepresented in pretty much all countries. I imagine this is a known issue so I'll just brainstorm some solutions here.

- Increase PROMOTION_SCALE in the defines.lua file (promotion in general seems awfully slow in general, even with 100% admin efficiency).
- Remove the -0.1% promotion chance for pops who do not follow the state religion if the state religion is atheism.
- Lower the admin efficiency hit caused by social reforms (if all social reforms are enacted you require 13% of the population to be bureaucrats if you want to retain 100% promotion efficiency, which is nearly unobtainable currently).
- Tie some social reforms to mid/late game techs to further help the AI with the issue above (an example is healthcare reforms requiring techs from the Medicine tech column, or environmental reforms requiring techs from the Power tech column).
- Speed up pop promotion if you have specific techs (not sure which but the Societal Trends tech column as a whole looks somewhat appropriate for this)
- Have the modifiers from the Export Oriented economy focus and Urbanisation development policy reduce RGO sizes.
- Have some techs from tech columns such as Market Functionality and Commodities (specially ones such as Green Revolution) reduce RGO sizes.
- Increase RGO_SUPPLY_DEMAND_FACTOR_FIRE in the defines.lua file from 0 to a small amount, probably something between 0.01 and 0.05. I can see this one causing more issues than the other solutions though.
- To counter some of these changes for countries and players that do wish to keep a rural society, have the Land Reform decision, Ruralisation National development policy and Import Substitution Industrialisation economy focus increase RGO sizes.
- Though not entirely related to this, each economic specialization should encourage pops to promote to specific pop types (services encourage clerks, consumer goods encourage craftsmen, heavy industry and military goods encourage both equally).
- Some countries, such as France, need to be fleshed out more when it comes to pops, with metropolitan France being a lot more rural than it should. Italy is a good example of a country with fleshed out pops and due to that  their industry skyrockets within the first decade of the game, but they do experience de-urbanization through the game. This issue is a lot more annoying as it'd take ages to fully fix the entire world's pop types and have them on the same level of Italy and Spain.

Let me know if this sounds interesting for the mod, I'll do a test run with some of these changes during the weekend and reply to this post with how the economy reacts to it.

**Comment by settintotrieste** [comment]
It’s a know issue but I decided to keep it the way it is because it will eventually lead to a overhaul of everything in the mod.

The main problem is that employed craftsmen contribute almost all industry score so if craftsmen pops are increased then the GP list will be messed up. I’ll need to then edit the prestige levels again for balance. 

Also, if there are too many craftsmen, factory output will completely outpace current demand. So pop demand or factory output has to be redone. 

A lot more factories will also strain the RGO capacity, especially with less RGO pops. RGO production will then need to be redone.

if there are too many craftsmen at the games start then there will be massive unemployment, causing huge immigration for the first 10 years which will mess with historical population growth. If factories are added to the game’s start to address this, the problem will be what factories to use.

More factories means more profit. This is going into the national bank which can get a stack overflow from having too much money. Reducing the value of money is not feasible because it is strangely tied to how likely rebels will rise up. Decision and events money values must also be reviewed to be attainable. Tweaking factory profits to be lower risks cascading bankruptcies when the market is just slightly lower or higher.

Factories in this mod a much more productive then vanilla ones due to the gazillion modifiers and techs. To rebalance them would need to review all of them.

More factories also cause more lag.

More craftsmen also decisively shifts those heavily urbanised nations in favour of socialism. It is difficult to mod ideological development in the game so craftsmen are set to be more socialist in general. This would affect some decisions and events. If ideology was made more dynamic, the problem then becomes what criteria to use and whether the AI can replicate those criteria.

None of the problems above can be tackled in isolation, it’s a giant vicious cycle if the pop levels are done incorrectly. 

I think it is better not to touch the economy too much in this mod because it’s like a stack of cards.
