### ISSUE TITLE
Apocalyptic Republican Fury Issues (and ideas)

### ISSUE THREAD

**Issue by vegku** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#812]
In event 8015874, Cascadia and New England does not spawn even when I change the chance to 100% on my own end. 

I've attempted to run the command multiple times in the console with no luck. Is Cascadia or New England meant to spawn in later in the war? 

Alternatively, I have noticed that California declares war on the United States, causing any US allies to declare war on California. In a potential civil war against a Trumpist federal government, it seems highly unplausible that US allies would be rushing to intervene. 

Also, would there be any chance in the future for heavily democratic states such as Illinois, Pennyslvania, New York, New Jersey, Delaware, and maybe Maryland break away? Perhaps form something similar to the Free American States that happen in the Biden civil war path. Maybe we could get another event that can trigger parts of New Afrika spawning too. 

Perhaps also it might be interesting to see that a Trumpist USA after overthrowing Biden, to see a rise in infamy for overthrowing an elected president. Maybe it could trigger an event similar to the Great Recession where the world has a lot of economic uncertainty with the US at war internally

Final question, what is the Western American States meant to do? I have been unable to find any files in the mod that indicate how to get it to spawn?

**Comment by settintotrieste** [comment]
Okay I've done a tweak to make it such that there is an 80% chance of a civil war one between the Free States of America under Biden (states that voted democrat) and the normal USA (Trump country). New Afrika cores will get a huge militancy gain to stimulate the african american pops to revolt for independence there.

The Western American States is there just for dismantle CB wars so that the USA can be more effectively dismantled.
