### ISSUE TITLE
Migration is broken

### ISSUE THREAD

**Issue by GuiHubner13** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#814]
I was playing as Brazil and I dont receive any immigrant,now my population is falling down and i dont receive immigrants to keep my poulation growing,the only nations that receive immigrants are the US and Canada, even though I'm selecting reforms to improve my immigration rate, and not if it's just me or the mod version, whoever can help me, thank you.

**Comment by settintotrieste** [comment]
It could be due to numerous factors that may not be due to broken mechanics like rising militancy, unemployment, change in citizenship policy, change in gov type, selection of decisions which lower immigration attraction or other nations received modifiers that increased their attraction, country entering a war, pop needs being unmet etc
