### ISSUE TITLE
Are the populists supposed to be fascist now?

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#824]
I've noticed that you made the German nazi flag a populist flag again; do you plan to make fascism/naziism a subset of populism in the future? What are your plans for the nationalist parties?

**Comment by settintotrieste** [comment]
No, populist is still intended to be the same as it was prior. I would say that right now, fascism is subsumed under the nationalist ideology instead. The change to the German flag was really just to avoid the situation where the flag of democracy1 is the nazi flag due to coding reasons that make nationalist_dictatorship (sectarian regime) share the same flag with democracy1.
