### ISSUE TITLE
Purpose of arab_saharan culture?

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#852]
The arab_saharan culture isn't included in the Pan-Arab decision chain and isn't present in the 1992 start. It could be reverted back to the Tuareg and African Minor cultures found in base Victoria 2.

**Comment by ccfox** [comment]
In my opinion, the better solution would probably be to replace it with Hassaniya Arabic (Which is used for other countries in the area) for the 'Saharan' pops in Southern Algeria and Northern Mali (since from what I can tell that's what its supposed to be in those places if you look at the range of Hassaniya Arabic) - and with either Sudanese or the Pan-Arab culture for northern Niger (since the Diffa Arabs are related to the Sudanese, but might be represented better with the pan-Arab culture). As well as, of course, making those changes consistent with the 1992 start date.

**Comment by settintotrieste** [comment]
@ccfox's suggestion looks good.
