### ISSUE TITLE
RGO Output issue in Palermo province(Sicily-Italy)-Edited: other trade-goods icons glitch around the world

### ISSUE THREAD

**Issue by aurreko** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#857]
In Palermo province there is a bug related to RGO output: fish is the province trade-good but the icon is displayed on the Gulf of Gabes and there isn't any interaction with that and POP, no fishes, no money from selling, no pop province works on the good. To explain better i attach two screenshots, one from vanilla game, where it all works fine, and other from 1946 bookmark CWE. Some some additional info: 1)In either Vanilla bookmarks it's all ok-2)All CWE bookmarks, playing as Italy, are affected by this glitch since start-3)Bug occurs with both integrated and dedicated GPU(i have a laptop)-4)I tried various video settings and nothing changes; i attach also a CWE setting-5)Vanilla map cache deleted before to run your mod and no other mod installed-6)CWE versions tested are latest official release 1.14 and yesterday master zip beta version downloaded from this site. Sorry for my english and ask if you want more info.

EDIT: this glitch affects also other provinces but only icons are displayed wrongly, trade goods interacted as supposed with pops. I add a screenshot of Dutch Celibes in 1946.

[CWE settings.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/8184872/CWE.settings.txt)

![CWE](https://user-images.githubusercontent.com/80220181/156743686-a9ecf662-0e90-4c48-ae9b-1ac49461d7de.JPG)

![Vanilla](https://user-images.githubusercontent.com/80220181/156743729-6e06a3bb-a6d4-4275-989f-d80490e8cdab.JPG)

![Celebes](https://user-images.githubusercontent.com/80220181/157028738-b79c952e-6299-49cf-8008-0c6a4574db3d.JPG)

**Comment by settintotrieste** [comment]
I think there is no way to fix the UI issue as the goods icons are set to be displayed equidistant from all corners of the province. The only alternative is to change the province shapes but that would reduce map accuracy.

Regarding the RGOs not employing anyone, it is due to oversupply of the RGO's good which causes the RGO to fire its employees or not hire anyone. Usually the oversupply issue should start to go down after around 10 years (around 1956 if you used the 1946 start) so empty RGOs should start to hire pops after that. For Palermo, it could be that the province does not have any farmers and only craftsmen.

**Comment by aurreko** [comment]
Ok. Understood. Many thanks for the reply; your mod is the best cold war overhaul for PDX games, IMHO.
